# default parameters used in routes.py and sql.py

title: Title
slogan: Slogan
header_title: Esther
footer_text: Esther © 2024. All rights reserved.
footer_right: If you have any questions about Esther or would like to withdraw your data or participation from Esther, please contact our lead investigator at tb2249@bath.ac.uk.
timeout: 5

# advised to keep these as true and override in routes.py where required

header: true
footer: true
back: true
logout: true
